Table SUBGRUPO_GMUS {
  id_subgrupo int [pk, increment]
  codigo_gmus int
  nome varchar
}


Table MEDICAMENTO {
  id_medicamento int [pk, increment]
  codigo_gmus varchar [not null]
  descricao varchar [not null]
  unidade varchar
  subgrupo_gmus_id int
}


Table PRINCIPIO_ATIVO {
  id_principio_ativo int [pk, increment]
  nome varchar [not null]
}


Table MEDICAMENTO_PRINCIPIO_ATIVO {
  medicamento_id int [not null]
  principio_ativo_id int [not null]


  indexes {
    (medicamento_id, principio_ativo_id) [pk]
  }
}


Table CLASSIFICACAO {
  id_classificacao int [pk, increment]
  nome varchar [not null]
  cor varchar
  descricao varchar
  ativo boolean
}


Table MEDICAMENTO_CLASSIFICACAO {
  medicamento_id int [not null]
  classificacao_id int [not null]


  indexes {
    (medicamento_id, classificacao_id) [pk]
  }
}


Table UPS {
  id_ups int [pk, increment]
  codigo_gmus varchar [not null, unique]
  nome varchar [not null]
}


Table COMPETENCIA {
  id_competencia int [pk, increment]
  mes int [not null]
  ano int [not null]


  indexes {
    (mes, ano) [unique]
  }
}


Table LOTE {
  id_lote int [pk, increment]
  medicamento_id int [not null]
  codigo_lote varchar [not null]
  data_validade date
}


Table USUARIO {
  id_usuario int [pk, increment]
  nome varchar [not null]
  email varchar [not null, unique]
  senha varchar [not null]
  ativo boolean
}


Table SESSAO {
  id_sessao int [pk, increment]
  usuario_id int [not null]
  token varchar [not null]
  data_criacao datetime [not null]
  data_expiracao datetime
  ultimo_acesso datetime
}


Table IMPORTACAO {
  id_importacao int [pk, increment]
  nome_arquivo varchar [not null]
  tipo_relatorio varchar
  data_importacao datetime [not null]
  status varchar [not null]


  usuario_id int [not null]
  competencia_id int [not null]
  ups_id int [not null]
}


Table ESTOQUE {
  id_estoque int [pk, increment]


  medicamento_id int [not null]
  ups_id int [not null]
  competencia_id int [not null]
  lote_id int
  importacao_id int [not null]


  quantidade decimal [not null]
}


/* RELACIONAMENTOS */


Ref: MEDICAMENTO.subgrupo_gmus_id > SUBGRUPO_GMUS.id_subgrupo
Ref: LOTE.medicamento_id > MEDICAMENTO.id_medicamento
Ref: MEDICAMENTO_PRINCIPIO_ATIVO.medicamento_id > MEDICAMENTO.id_medicamento
Ref: MEDICAMENTO_PRINCIPIO_ATIVO.principio_ativo_id > PRINCIPIO_ATIVO.id_principio_ativo


Ref: MEDICAMENTO_CLASSIFICACAO.medicamento_id > MEDICAMENTO.id_medicamento
Ref: MEDICAMENTO_CLASSIFICACAO.classificacao_id > CLASSIFICACAO.id_classificacao


Ref: SESSAO.usuario_id > USUARIO.id_usuario


Ref: IMPORTACAO.usuario_id > USUARIO.id_usuario
Ref: IMPORTACAO.competencia_id > COMPETENCIA.id_competencia
Ref: IMPORTACAO.ups_id > UPS.id_ups


Ref: ESTOQUE.medicamento_id > MEDICAMENTO.id_medicamento
Ref: ESTOQUE.ups_id > UPS.id_ups
Ref: ESTOQUE.competencia_id > COMPETENCIA.id_competencia
Ref: ESTOQUE.lote_id > LOTE.id_lote
Ref: ESTOQUE.importacao_id > IMPORTACAO.id_importacao

