# Generated by Django 5.0.14 on 2026-08-16 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('tipo_relatorio', models.CharField(blank=True, max_length=80)),
                ('data_importacao', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes', to='core.competencia')),
                ('ups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes', to='core.ups')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'importacao',
                'verbose_name_plural': 'importacoes',
                'ordering': ['-data_importacao', 'nome_arquivo'],
            },
        ),
    ]
