# Generated by Django 5.0.14 on 2026-08-16 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_localizacaoestoque'),
        ('importacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='hash_arquivo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='importacao',
            name='status',
            field=models.CharField(choices=[('concluida', 'Concluida'), ('concluida_com_alertas', 'Concluida com alertas')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='importacao',
            constraint=models.UniqueConstraint(fields=('competencia', 'ups', 'tipo_relatorio'), name='unique_importacao_competencia_ups_tipo'),
        ),
    ]
