# Generated by Django 5.0.14 on 2026-08-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0002_importacao_hash_arquivo_alter_importacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacao',
            name='status',
            field=models.CharField(choices=[('concluida', 'Concluida'), ('concluida_com_alertas', 'Concluida com alertas'), ('concluida_parcial', 'Concluida parcial')], max_length=50),
        ),
    ]
