# Generated by Django 5.0.14 on 2026-08-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('importacoes', '0001_initial'),
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=120)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='medicamentos.medicamento')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': ['medicamento__descricao', 'codigo_lote', 'data_validade'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='core.competencia')),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='importacoes.importacao')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='core.localizacaoestoque')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='medicamentos.medicamento')),
                ('ups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='core.ups')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='estoques.lote')),
            ],
            options={
                'verbose_name': 'estoque',
                'verbose_name_plural': 'estoques',
                'ordering': ['medicamento__descricao', 'competencia', 'ups'],
            },
        ),
    ]
