# Generated by Django 5.0.14 on 2026-08-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='localizacao',
        ),
    ]
