# Generated by Django 5.0.14 on 2026-08-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('cor', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'classificacao',
                'verbose_name_plural': 'classificacoes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PrincipioAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'principio ativo',
                'verbose_name_plural': 'principios ativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SubgrupoGmus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_gmus', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'subgrupo GMUS',
                'verbose_name_plural': 'subgrupos GMUS',
                'ordering': ['nome', 'codigo_gmus'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_gmus', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('unidade', models.CharField(blank=True, max_length=80)),
                ('classificacoes', models.ManyToManyField(blank=True, related_name='medicamentos', to='medicamentos.classificacao')),
                ('principios_ativos', models.ManyToManyField(blank=True, related_name='medicamentos', to='medicamentos.principioativo')),
                ('subgrupo_gmus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='medicamentos.subgrupogmus')),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
                'ordering': ['descricao', 'codigo_gmus'],
            },
        ),
    ]
