# Generated by Django 5.0.14 on 2026-08-16 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'competencia',
                'verbose_name_plural': 'competencias',
                'ordering': ['-ano', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='LocalizacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'localizacao de estoque',
                'verbose_name_plural': 'localizacoes de estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_gmus', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'UPS',
                'verbose_name_plural': 'UPS',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='competencia',
            constraint=models.CheckConstraint(check=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='check_competencia_mes_entre_1_e_12'),
        ),
        migrations.AddConstraint(
            model_name='competencia',
            constraint=models.UniqueConstraint(fields=('ano', 'mes'), name='unique_competencia_ano_mes'),
        ),
    ]
