# Generated by Django 5.0.14 on 2026-08-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('estoques', '0002_remove_estoque_localizacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalizacaoEstoque',
        ),
    ]
