# Generated by Django 5.0.14 on 2026-08-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_localizacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='ups',
            name='compoe_estoque_convencional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ups',
            name='participa_competencia',
            field=models.BooleanField(default=True),
        ),
    ]
