# Generated by Django 5.0.14 on 2026-08-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ups_compoe_estoque_convencional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ups',
            name='id_unidade_gmus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ups',
            name='codigo_gmus',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='ups',
            constraint=models.UniqueConstraint(fields=('codigo_gmus', 'id_unidade_gmus'), name='unique_ups_codigo_id_unidade_gmus'),
        ),
    ]
